model:
  default: Qwen3-4B-Instruct

LLM:
  Qwen3-4B-Instruct:
    link: Qwen/Qwen3-4B-Instruct-2507
    max_new_tokens: 1024
    repetition_penalty: 1.05
    prompt_path: configs/prompt/span_extraction.jinja

  Qwen3-8B:
    link: Qwen/Qwen3-8B
    max_new_tokens: 1024
    repetition_penalty: 1.05
    prompt_path: configs/prompt/span_extraction.jinja