model:
  type: GLINER
  default: multi-v2.1

LLM:
  Qwen3-4B-Instruct:
    link: Qwen/Qwen3-4B-Instruct-2507
    max_new_tokens: 1024
    repetition_penalty: 1.05
    prompt_path: configs/prompt/span_extraction.jinja

  Qwen3-8B:
    link: Qwen/Qwen3-8B
    max_new_tokens: 1024
    repetition_penalty: 1.05
    prompt_path: configs/prompt/span_extraction.jinja

GLINER:
  multi-v2.1:
    link: urchade/gliner_multi-v2.1
    threshold: 0.5
  
  bi-base-v2.0:
    link: knowledgator/gliner-bi-base-v2.0
    threshold: 0.5